spring:
  application:
    name: hesco-backend

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hesco_local}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:8084}

logging:
  level:
    com.lmkr.hesco: INFO
